point_cloud_generator_options:
    # Scene sampling mode 0 = num_rays surface points randomly uniformly across faces of specified model, or all of them (don't specify model)
    # scene sampling mode 10 = dim_x by dim_y raycasted points
    scene_sampling_mode: 0
    
    x_dim: 320
    x_fov: 90
    y_dim: 240
    y_fov: 90
    max_range: 10.0
    num_rays: 10000

    models:
       #- urdf: "models/urdf/cubes_jointed.urdf"
       #  q0: [0.1, 0, 0.5, 0.9, 0.5, 0.2, 0.2]
       #- urdf: "models/urdf/cubes.urdf"
       #  q0: [0.0, 0.0, 2.0, 0.9, 0.5, 0.2, 1.0, 1.0, 1.0, 0.8, 0.5, -0.2]
       #- urdf: "models/urdf/bunny.urdf"
       #  q0: [0.2, 0.2, 0.2, 1.57, 0.0, 0.0]
       - urdf: "models/urdf/cube.urdf"
         q0: [0.0, 0, 0.0, 0.0, 0.0, 0.0]